import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { images, PageHero } from "../components/site";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [
  { title: "Services — Abdul Moiez Mirza Architects" }, { name: "description", content: "Architectural design, interiors, sustainability, planning and visualization in Islamabad." },
  { property: "og:title", content: "Services — Abdul Moiez Mirza Architects" }, { property: "og:description", content: "Architectural design, interiors, sustainability, planning and visualization in Islamabad." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: Services });

const services = [
 ["Architectural Design", "Complete design services from early ideas and feasibility through detailed documentation.", images.detail], ["Residential Architecture", "Bespoke houses shaped around family life, privacy, light, and landscape.", images.residence], ["Commercial Architecture", "Distinctive offices, retail environments, and mixed-use destinations.", images.commercial], ["Interior Design", "Integrated spaces, materials, lighting, furniture, and crafted detail.", images.interior], ["Sustainable Architecture", "Climate-responsive design that reduces demand and strengthens connection to nature.", images.sustainable], ["3D Visualization", "Photoreal architectural storytelling that makes design decisions clear before construction.", images.visualization], ["Space Planning", "Efficient, intuitive spatial organization for homes and workplaces.", images.interior], ["Urban Planning", "Connected, walkable environments structured by landscape and public life.", images.urban], ["Renovation & Remodeling", "Thoughtful transformation of existing buildings, preserving character while enabling new use.", images.renovation], ["Design Consultation", "Focused professional direction for sites, concepts, materials, and design decisions.", images.detail], ["Project Planning", "Clear scope, phasing, coordination, and technical pathways from concept to site.", images.urban], ["Architectural Execution", "Close design oversight to protect quality and intent during construction.", images.commercial],
] as const;
function Services() { return <main><PageHero eyebrow="WHAT WE DO" title="From first line to final detail." image={images.commercial} /><section className="services-intro"><p className="eyebrow">AN INTEGRATED PRACTICE</p><p>We combine strategic thinking, architectural imagination, and technical precision to create spaces that perform beautifully.</p></section><section className="service-list">{services.map((s,i)=><article className={`service-row reveal ${i%2 ? "reverse" : ""}`} key={s[0]}><div className="service-image"><img src={s[2]} alt={s[0]} loading="lazy" width={1920} height={1080}/></div><div><span>{String(i+1).padStart(2,"0")}</span><h2>{s[0]}</h2><p>{s[1]}</p><a href="mailto:studio@ammarchitects.pk?subject=Service enquiry">Discuss this service <ArrowUpRight size={17}/></a></div></article>)}</section></main> }